server:
  #  端口配置
  port: 9091
#  servlet:
#    项目名称
#    context-path: /spring-boot
  tomcat:
    accesslog:
      buffered: true
      directory: E:/logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log


#beetl前缀与后缀
#beetl:
#   templatesPath: /views/
#   suffix: html  此种方式controll 地址必须加入html，不采用

#reids
spring:
  redis:
    host: 127.0.0.1
    port: 6379


#mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hlfc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  #kafka
  # 指定kafka 代理地址，可以多个
  kafka:
    bootstrap-servers: 192.168.47.130:9092,192.168.47.131:9092,192.168.47.132:9092
    # 指定默认消费者group id
    consumer:
      group-id: test
    # 指定默认topic id
    template:
      default-topic: my-replicated-topic
    # 指定listener 容器中的线程数，用于提高并发量
    listener:
      concurrency: 3
    # 每次批量发送消息的数量
    producer:
      batch-size: 1000
      #key-value序列化反序列化
      #spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
      #spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
      #spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
      #spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 524288

#开启Mybatis下划线命名转驼峰命名
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true

#mybatis plus
mybatis-plus:
  mapper-locations: classpath:mybatisplus/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hlfc.springboot.db.mybatisplus.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false



