server:
  #  端口配置
  port: 9091
  servlet:
#    项目名称
    context-path: /spring-boot


#beetl前缀与后缀
#beetl:
#   templatesPath: /views/
#   suffix: html  此种方式controll 地址必须加入html，不采用


spring:
  redis:
    host: 127.0.0.1
    port: 6379