server:
  #  端口配置
  port: 9091
#  servlet:
#    项目名称
#    context-path: /spring-boot
  tomcat:
    accesslog:
      buffered: true
      directory: E:/logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log


#beetl前缀与后缀
#beetl:
#   templatesPath: /views/
#   suffix: html  此种方式controll 地址必须加入html，不采用


spring:
  redis:
    host: 127.0.0.1
    port: 6379


#mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hlfc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


#开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true